<?php

namespace Pardot\Exercise\Tests;

use Pardot\Exercise\AdditiveFunctionValidator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-29 at 22:32:13.
 */
class AdditiveFunctionValidatorTest extends \PHPUnit_Framework_TestCase
{
    private $primes = [
        2,
        3,
        5,
        7,
    ];

    public function testFunctionIsAdditive()
    {
        $isAdditive = function ($x) {
            return $x;
        };

        $this->assertTrue(AdditiveFunctionValidator::isAdditive($isAdditive, 2, 3));
    }

    public function testFunctionIsNotAdditive()
    {
        $isNotAdditive = function ($x) {
            return $x + 1;
        };

        $this->assertFalse(AdditiveFunctionValidator::isAdditive($isNotAdditive, 2, 3));
    }
}
